apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: deployment-cmis-hr
    module: cmis-hr
    type: prod
  name: cmis-hr-prod
  namespace: ns-prod
spec:
  progressDeadlineSeconds: 60
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: pod-cmis-hr
      type: prod
      module: cmis-hr
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: pod-cmis-hr
        type: prod
        module: cmis-hr
    spec:
      containers:
      - image: 10.232.58.90:8000/cmis-prod/cmis-hr:latest
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /cmis-hr/a/login
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 120
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 3
        name: cmis-hr-prod
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /cmis-hr/a/login
            port: 8080
            scheme: HTTP
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 3
        resources: 
          requests:
            memory: "1024Mi"
            cpu: "250m"
          limits: 
            memory: "2048Mi"
            cpu: "500m"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /usr/local/share
          name: cmis-local-dir
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
      - name: cmis-local-dir
        hostPath: 
          path: /mnt/share_54_f/
          type: Directory

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: svc-cmis-hr
    module: cmis-hr
    type: prod
  name: cmis-hr-prod
  namespace: ns-prod
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: pod-cmis-hr
    type: prod
    module: cmis-hr
  sessionAffinity: None
  type: ClusterIP
