apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        health
        kubernetes cluster.local in-addr.arpa ip6.arpa {
           pods insecure
           upstream 10.232.58.36
           fallthrough in-addr.arpa ip6.arpa
           ttl 30
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"Corefile":".:53 {\n    errors\n    health\n    kubernetes cluster.local in-addr.arpa ip6.arpa {\n       pods insecure\n       upstream 10.232.58.36\n       fallthrough in-addr.arpa ip6.arpa\n       ttl 30\n    }\n    prometheus :9153\n    forward . /etc/resolv.conf\n    cache 30\n    loop\n    reload\n    loadbalance\n}\n"},"kind":"ConfigMap","metadata":{"annotations":{},"creationTimestamp":"2019-07-31T02:09:05Z","name":"coredns","namespace":"kube-system","resourceVersion":"2392415","selfLink":"/api/v1/namespaces/kube-system/configmaps/coredns","uid":"f9ef2337-1b0b-424d-9c5c-e7e89333a64e"}}
  creationTimestamp: "2019-07-31T02:09:05Z"
  name: coredns
  namespace: kube-system
  resourceVersion: "2475295"
  selfLink: /api/v1/namespaces/kube-system/configmaps/coredns
  uid: f9ef2337-1b0b-424d-9c5c-e7e89333a64e
