apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-1g-01
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.232.58.36
    path: "/mnt/sdc1/k8s-pv/pv-nfs-1g-01"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-1g-02
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.232.58.36
    path: "/mnt/sdc1/k8s-pv/pv-nfs-1g-02"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-20g-01
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.232.58.36
    path: "/mnt/sdc1/k8s-pv/pv-nfs-20g-01"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-20g-02
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.232.58.36
    path: "/mnt/sdc1/k8s-pv/pv-nfs-20g-02"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-20g-03
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.232.58.36
    path: "/mnt/sdc1/k8s-pv/pv-nfs-20g-03"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-50g-01
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 10.232.58.36
    path: "/mnt/sdc1/k8s-pv/pv-nfs-50g-01"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-50g-02
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 10.232.58.36
    path: "/mnt/sdc1/k8s-pv/pv-nfs-50g-02"

---


apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-50g-03
spec:
  storageClassName: manual
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 10.232.58.36
    path: "/mnt/sdc1/k8s-pv/pv-nfs-50g-03"

