apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: deployment-cmis-static-f
    module: cmis-static-f
    type: prod
  name: cmis-static-f-prod
  namespace: ns-prod
spec:
  progressDeadlineSeconds: 15
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: pod-cmis-static-f
      type: prod
      module: cmis-static-f
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: pod-cmis-static-f
        type: prod
        module: cmis-static-f
    spec:
      containers:
      - image: 10.232.58.90:8000/cmis-prod/cmis-static-f:latest
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /index.html
            port: 80
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 3
        name: cmis-static-f-prod
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /index.html
            port: 80
            scheme: HTTP
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 3
        resources: 
          requests:
            memory: "512Mi"
            cpu: "125m"
          limits: 
            memory: "1024Mi"
            cpu: "250m"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: svc-cmis-static-f
    module: cmis-static-f
    type: prod
  name: cmis-static-f-prod
  namespace: ns-prod
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: pod-cmis-static-f
    type: prod
    module: cmis-static-f
  sessionAffinity: None
  type: ClusterIP
