apiVersion: v1
kind: Service
metadata:
  labels:
    app: activemq
    type: prod
  name: activemq
  namespace: ns-middware-prod
spec:
  ports:
  - name: p1
    port: 8161
    protocol: TCP
    targetPort: 8161
  - name: p2
    port: 61616
    protocol: TCP
    targetPort: 61616
  selector:
    app: activemq
    type: prod
  sessionAffinity: None
  type: NodePort

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: activemq
    type: prod
  name: activemq-prod
  namespace: ns-middware-prod
spec:
  progressDeadlineSeconds: 180
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: activemq
      type: prod
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: activemq
        type: prod
    spec:
      containers:
      - image: rmohr/activemq:5.15.6-alpine 
        imagePullPolicy: IfNotPresent
        name: cmis-all-prod
        ports:
        - containerPort: 8161
          name: p1
          protocol: TCP
        - containerPort: 61616
          name: p2
          protocol: TCP
      dnsPolicy: ClusterFirst
      restartPolicy: Always
